### ISSUE TITLE
Fix adorable mistake

### ISSUE THREAD

**Issue by pickfire** [jgm/CommonMark#391] opened 2016-02-02 12:19 UTC
Hi, I found that the latest version of spec.commonmark.org is last written 2015-01-12 and the older version is written even later. Isn't it funny?

Good luck and have a nice day!

**Comment by cebe** [comment] 2016-02-02 14:48
duplicate of #388 and fixed by https://github.com/jgm/CommonMark/commit/039157d8a65d8476368657ce372f458266460ca7 already.

**Comment by pickfire** [comment] 2016-02-03 05:19
@cebe, but why is the website still showing the wrong time?

**Comment by jgm** [comment] 2016-02-03 05:45
We just haven't done a release since the change was made.

+++ Ivan Tham [Feb 02 16 21:19 ]:

**Closed** 2016-02-03 18:50 UTC
