### ISSUE TITLE
Translate the spec into Chinese

### ISSUE THREAD

**Issue by yanxyz** [jgm/CommonMark#309] opened 2015-03-10 04:40 UTC
Hi, I've translated the spec into Chinese. 
https://github.com/yanxyz/commonmark-spec/

When building the HTML version of the spec, there are some warnings.  However, it's not because the fault of document, but the lack of  considering non-English language. You can try yourself if you are interesting.

Then some questions:

In the words“delimiter run", what's the meaning of "run"?

In the section of "Emphasis and strong emphasis",  is "iff" the typo of "if"?

In line 3093 is "\*L\*" the typo of "\*Ls\*"?

Modifying the words "M is a list marker M of width W" to "M is a list marker, M of width is W" maybe better.

**Comment by jgm** [comment] 2015-03-10 05:01
+++ yan [Mar 09 15 21:40 ]:
>Hi, I've translated the spec into Chinese.
>https://github.com/yanxyz/commonmark-spec/

Fantastic!

>When building the HTML version of the spec, there are some warnings.  However, it's not because the fault of document, but the lack of  considering non-English language. You can try yourself if you are interesting.

I get these warnings:
```
WARNING: internal link with no anchor '%E5%89%8D%E8%A8%80'
WARNING: internal link with no anchor '%E4%BB%80%E4%B9%88%E6%98%AF-markdown-'
WARNING: internal link with no anchor '%E4%B8%BA%E4%BB%80%E4%B9%88%E9%9C%80%E8%A6%81%E8%A7%84%E8%8C%83-'
WARNING: internal link with no anchor '%E5%85%B3%E4%BA%8E%E6%9C%AC%E6%96%87%E6%A1%A3'
WARNING: internal link with no anchor '%E9%A2%84%E5%A4%87'
WARNING: internal link with no anchor '%E5%AD%97%E7%AC%A6%E4%B8%8E%E8%A1%8C'
WARNING: internal link with no anchor '%E5%88%B6%E8%A1%A8%E7%AC%A6'
WARNING: internal link with no anchor '%E5%9D%97%E4%B8%8E%E5%86%85%E8%81%94%E5%85%83%E7%B4%A0'
WARNING: internal link with no anchor '%E4%BC%98%E5%85%88%E7%BA%A7'
WARNING: internal link with no anchor '%E5%AE%B9%E5%99%A8%E5%9D%97%E5%92%8C%E5%8F%B6%E5%9D%97'
WARNING: internal link with no anchor '%E5%8F%B6%E5%9D%97'
WARNING: internal link with no anchor '%E6%B0%B4%E5%B9%B3%E7%BA%BF'
WARNING: internal link with no anchor 'atx-%E5%BC%8F%E6%A0%87%E9%A2%98'
WARNING: internal link with no anchor 'setext-%E5%BC%8F%E6%A0%87%E9%A2%98'
WARNING: internal link with no anchor '%E7%BC%A9%E8%BF%9B%E5%BC%8F%E4%BB%A3%E7%A0%81%E5%9D%97'
WARNING: internal link with no anchor '%E5%9B%B4%E6%A0%8F%E5%BC%8F%E4%BB%A3%E7%A0%81%E5%9D%97'
WARNING: internal link with no anchor 'html-%E5%9D%97'
WARNING: internal link with no anchor '%E9%93%BE%E6%8E%A5%E5%BC%95%E7%94%A8%E5%AE%9A%E4%B9%89'
WARNING: internal link with no anchor '%E6%AE%B5%E8%90%BD'
WARNING: internal link with no anchor '%E7%A9%BA%E8%A1%8C'
WARNING: internal link with no anchor '%E5%AE%B9%E5%99%A8%E5%9D%97'
WARNING: internal link with no anchor '%E5%9D%97%E5%BC%95%E7%94%A8'
WARNING: internal link with no anchor '%E5%88%97%E8%A1%A8%E9%A1%B9'
WARNING: internal link with no anchor '%E8%AE%A8%E8%AE%BA'
WARNING: internal link with no anchor '%E5%88%97%E8%A1%A8'
WARNING: internal link with no anchor '%E5%86%85%E8%81%94%E5%85%83%E7%B4%A0'
WARNING: internal link with no anchor '%E7%94%A8%E5%8F%8D%E6%96%9C%E6%9D%A0%E8%BD%AC%E4%B9%89'
WARNING: internal link with no anchor '%E5%AE%9E%E4%BD%93'
WARNING: internal link with no anchor '%E5%86%85%E8%81%94%E4%BB%A3%E7%A0%81'
WARNING: internal link with no anchor '%E5%BC%BA%E8%B0%83%E4%B8%8E%E7%9D%80%E9%87%8D%E5%BC%BA%E8%B0%83'
WARNING: internal link with no anchor '%E9%93%BE%E6%8E%A5'
WARNING: internal link with no anchor '%E5%9B%BE%E5%83%8F'
WARNING: internal link with no anchor '%E8%87%AA%E5%8A%A8%E9%93%BE%E6%8E%A5'
WARNING: internal link with no anchor '%E5%8E%9F%E7%94%9F-html'
WARNING: internal link with no anchor '%E7%A1%AC%E6%8D%A2%E8%A1%8C'
WARNING: internal link with no anchor '%E8%BD%AF%E6%8D%A2%E8%A1%8C'
WARNING: internal link with no anchor '%E6%96%87%E6%9C%AC%E5%86%85%E5%AE%B9'
WARNING: internal link with no anchor '%E9%99%84%E5%BD%95-a-%E8%A7%A3%E6%9E%90%E7%AD%96%E7%95%A5'
WARNING: internal link with no anchor '%E6%A6%82%E8%BF%B0'
WARNING: internal link with no anchor '%E6%96%87%E6%A1%A3%E6%A0%91'
WARNING: internal link with no anchor '%E8%BE%93%E5%85%A5%E8%A1%8C%E6%80%8E%E6%A0%B7%E6%94%B9%E5%8F%98%E6%96%87%E6%A1%A3%E6%A0%91'
WARNING: internal link with no anchor '%E4%BB%8E%E5%9D%97%E7%BB%93%E6%9E%84%E5%88%B0%E6%9C%80%E7%BB%88%E6%96%87%E6%A1%A3'
WARNING: internal link with no anchor 'setext-%E5%BC%8F%E6%A0%87%E9%A2%98'
WARNING: internal link with no anchor 'setext-%E5%BC%8F%E6%A0%87%E9%A2%98'
WARNING: internal link with no anchor 'setext-%E5%BC%8F%E6%A0%87%E9%A2%98'
WARNING: internal link with no anchor '%E5%9B%BE%E5%83%8F'
WARNING: internal link with no anchor '%E9%93%BE%E6%8E%A5%E5%BC%95%E7%94%A8%E5%AE%9A%E4%B9%89'
WARNING: internal link with no anchor '%E5%88%97%E8%A1%A8'
WARNING: internal link with no anchor '%E5%9D%97%E5%BC%95%E7%94%A8'
WARNING: internal link with no anchor '%E5%88%97%E8%A1%A8%E9%A1%B9'
WARNING: internal link with no anchor '%E5%88%97%E8%A1%A8'
WARNING: internal link with no anchor '%E9%99%84%E5%BD%95-a-%E8%A7%A3%E6%9E%90%E7%AD%96%E7%95%A5'
WARNING: internal link with no anchor '%E5%9D%97%E5%BC%95%E7%94%A8'
WARNING: internal link with no anchor '%E5%88%97%E8%A1%A8%E9%A1%B9'
WARNING: internal link with no anchor '%E5%9B%B4%E6%A0%8F%E5%BC%8F%E4%BB%A3%E7%A0%81%E5%9D%97'
WARNING: internal link with no anchor '%E5%88%97%E8%A1%A8%E9%A1%B9'
WARNING: internal link with no anchor '%E5%9D%97%E5%BC%95%E7%94%A8'
WARNING: internal link with no anchor '%E5%88%97%E8%A1%A8%E9%A1%B9'
WARNING: internal link with no anchor '%E5%9B%B4%E6%A0%8F%E5%BC%8F%E4%BB%A3%E7%A0%81%E5%9D%97'
WARNING: internal link with no anchor '%E5%9B%B4%E6%A0%8F%E5%BC%8F%E4%BB%A3%E7%A0%81%E5%9D%97'
WARNING: internal link with no anchor '%E5%86%85%E8%81%94%E4%BB%A3%E7%A0%81'
WARNING: internal link with no anchor '%E8%87%AA%E5%8A%A8%E9%93%BE%E6%8E%A5'
WARNING: internal link with no anchor '%E9%93%BE%E6%8E%A5%E5%BC%95%E7%94%A8%E5%AE%9A%E4%B9%89'
WARNING: internal link with no anchor '%E9%93%BE%E6%8E%A5%E5%BC%95%E7%94%A8%E5%AE%9A%E4%B9%89'
WARNING: internal link with no anchor '%E9%93%BE%E6%8E%A5%E5%BC%95%E7%94%A8%E5%AE%9A%E4%B9%89'
WARNING: internal link with no anchor '%E9%93%BE%E6%8E%A5%E5%BC%95%E7%94%A8%E5%AE%9A%E4%B9%89'
WARNING: duplicate reference link '[叶块]'
WARNING: duplicate reference link '[水平线]'
WARNING: duplicate reference link '[ATX 式标题]'
WARNING: duplicate reference link '[SETEXT 式标题]'
WARNING: duplicate reference link '[缩进式代码块]'
WARNING: duplicate reference link '[围栏式代码块]'
WARNING: duplicate reference link '[HTML 块]'
WARNING: duplicate reference link '[链接引用定义]'
WARNING: duplicate reference link '[段落]'
WARNING: duplicate reference link '[空行]'
WARNING: duplicate reference link '[容器块]'
WARNING: duplicate reference link '[块引用]'
WARNING: duplicate reference link '[列表]'
WARNING: duplicate reference link '[内联元素]'
WARNING: duplicate reference link '[内联代码]'
WARNING: duplicate reference link '[自动链接]'
WARNING: duplicate reference link '[硬换行]'
```

Need to look into these.

>Then some questions:
>
>In the words“delimiter run", what's the meaning of "run"?

See definition 4.3 from http://www.oxforddictionaries.com/us/definition/american_english/run
for "run" as a noun: "A continuous stretch or length of something"

>In the section of "Emphasis and strong emphasis",  is "iff" the typo of "if"?

No, it is a standard abbreviation for "if and only if", but this should be made more explicit, as not everyone will know that.

>In line 3093 is "\*L\*" the typo of "\*Ls\*"?

Yes, I'll fix this now.

>Modifying the words "M is a list marker M of width W" to "M is a list marker, M of width is W" maybe better.

This is actually a typo:  "M" should be removed.  (Also in a couple other places.)
I've just pushed a fix for this.

Many thanks for this feedback.

**Comment by yanxyz** [comment] 2015-03-10 06:21
Yes, The warnings is out during the generation of TOC, I think it should be ignored.

**Closed** 2015-03-10 11:46 UTC

**Comment by jgm** [comment] 2015-03-10 16:41
+++ yan [Mar 09 15 23:21 ]:
>Yes, The warnings is out during the generation of TOC, I think it should be ignored.

Do the TOC links, and the links corresponding to the "duplicate
reference link" warnings, work correctly?  If so, then the problem is
just with the generation of warnings.  (It should still presumably
be fixed in make_spec.py.)  If not, then the problem is in the
generation of links.

**Comment by yanxyz** [comment] 2015-03-11 00:21
The links work well.

"internal link with no anchor " , for instance,  the URL-encoded string '%E5%8F%B6%E5%9D%97' is "叶块”, this anchor links to the header "# 叶块“.

 "duplicate reference link" , for instance, There is "\[叶块](@leaf-block)" and also "# 叶块", so it is considered as duplicate.

**Comment by jgm** [comment] 2015-03-11 00:26
+++ yan [Mar 10 15 17:21 ]:
>   The links work well.
>
>   "internal link with no anchor " , for instance, the URL-encoded string
>   '%E5%8F%B6%E5%9D%97' is "叶块”, this anchor links to the header "# 叶块“.
>
>   "duplicate reference link" , for instance, There is "[叶块](@leaf-block)"
>   and also "# 叶块", so it is considered as duplicate.

Ah yes, we have a few cases where the header is plural and
the anchor to the term is singular, and Chinese won't make
that distinction.
